## Linear Regression model on Car prices Dataset by Keshav Verma

importing the required libraries and modules

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


I have uploaded the dataset on google drive and made it public and thereafter fetched the dataset in colab notebook using the following method

In [ ]:
# https://drive.google.com/file/d/1tzV9vkxEx6e7jytcz3HR7pT482D6BcxA/view?usp=sharing

# Replacing FILE_ID with the actual ID from your link
# The FILE_ID is the part between /d/ and /view

file_id = "1tzV9vkxEx6e7jytcz3HR7pT482D6BcxA"
file_url = f"https://drive.google.com/uc?id={file_id}"


loading the dataset

In [ ]:
dataset = pd.read_csv(file_url)
X = dataset.iloc[:, [1,3,4,5,6,7,8]].values
y = dataset.iloc[:, 2].values

printing the structure of the dataset and printing first few entries of it

In [ ]:
dataset.info() # printing the summary of the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB


In [ ]:
dataset.head(10)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
5,vitara brezza,2018,9.25,9.83,2071,Diesel,Dealer,Manual,0
6,ciaz,2015,6.75,8.12,18796,Petrol,Dealer,Manual,0
7,s cross,2015,6.50,8.61,33429,Diesel,Dealer,Manual,0
8,ciaz,2016,8.75,8.89,20273,Diesel,Dealer,Manual,0
9,ciaz,2015,7.45,8.92,42367,Diesel,Dealer,Manual,0


In [ ]:
print(X)

[[2014 5.59 27000 ... 'Dealer' 'Manual' 0]
 [2013 9.54 43000 ... 'Dealer' 'Manual' 0]
 [2017 9.85 6900 ... 'Dealer' 'Manual' 0]
 ...
 [2009 11.0 87934 ... 'Dealer' 'Manual' 0]
 [2017 12.5 9000 ... 'Dealer' 'Manual' 0]
 [2016 5.9 5464 ... 'Dealer' 'Manual' 0]]


In [ ]:
print(y)

[ 3.35  4.75  7.25  2.85  4.6   9.25  6.75  6.5   8.75  7.45  2.85  6.85
  7.5   6.1   2.25  7.75  7.25  7.75  3.25  2.65  2.85  4.9   4.4   2.5
  2.9   3.    4.15  6.    1.95  7.45  3.1   2.35  4.95  6.    5.5   2.95
  4.65  0.35  3.    2.25  5.85  2.55  1.95  5.5   1.25  7.5   2.65  1.05
  5.8   7.75 14.9  23.   18.   16.    2.75  3.6   4.5   4.75  4.1  19.99
  6.95  4.5  18.75 23.5  33.    4.75 19.75  9.25  4.35 14.25  3.95  4.5
  7.45  2.65  4.9   3.95  5.5   1.5   5.25 14.5  14.73  4.75 23.   12.5
  3.49  2.5  35.    5.9   3.45  4.75  3.8  11.25  3.51 23.    4.    5.85
 20.75 17.    7.05  9.65  1.75  1.7   1.65  1.45  1.35  1.35  1.35  1.25
  1.2   1.2   1.2   1.15  1.15  1.15  1.15  1.11  1.1   1.1   1.1   1.05
  1.05  1.05  1.05  1.    0.95  0.9   0.9   0.75  0.8   0.78  0.75  0.75
  0.75  0.72  0.65  0.65  0.65  0.65  0.6   0.6   0.6   0.6   0.6   0.6
  0.6   0.6   0.55  0.55  0.52  0.51  0.5   0.5   0.5   0.5   0.5   0.48
  0.48  0.48  0.48  0.45  0.45  0.45  0.45  0.45  0.45 

data preprocessing

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3,4,5])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 0.0 1.0 ... 5.59 27000 0]
 [0.0 1.0 0.0 ... 9.54 43000 0]
 [0.0 0.0 1.0 ... 9.85 6900 0]
 ...
 [0.0 0.0 1.0 ... 11.0 87934 0]
 [0.0 1.0 0.0 ... 12.5 9000 0]
 [0.0 0.0 1.0 ... 5.9 5464 0]]


In [ ]:
print(X[0,:])

[0.0 0.0 1.0 1.0 0.0 0.0 1.0 2014 5.59 27000 0]


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train[:,8:10] = sc.fit_transform(X_train[:,8:10])
X_test[:,8:10] = sc.transform(X_test[:,8:10])

In [ ]:
print(X_train[0,:])

[0.0 0.0 1.0 0.0 1.0 0.0 1.0 2014 -0.7539366424914046 -0.5542794396416897
 0]


In [ ]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
print(y_pred)
print(y_test)

[ 7.46806811 -0.31005821  4.35568005  8.87859668 13.88942797  4.9336366
  3.65332896  1.42205947  5.24485941  4.71169956  2.46505739  1.58791997
  5.10757832  7.34940804  8.49896045 13.48541617  7.12529935  4.34066408
 -0.35002273  2.30125539  4.91697753  3.93932661  6.2862795   7.95183888
 -1.72689928  1.88190253 -0.70349177  0.83710334  0.08198624  6.94754018
  3.70913217  7.38172401  0.74325568  7.84846702  3.68291165  1.76735078
  5.58223741  6.95294432 -2.43659962  8.97168147  9.05832792 19.25925608
  4.4661264   3.98190766  6.64776434  9.68357315  0.1852323   1.64754571
  5.17980611  7.29883418  7.84234979  4.26785332  4.94307701 19.5898908
  1.71646645  1.29699731  0.34624944  2.20705793  3.53142158  0.89725117
  3.70820889  6.79464626  2.75267073 20.65125543  4.39517264  5.5950403
  8.9800344   7.23554745  2.97922171  2.80565728  4.00371067  3.08036723
  1.73986178  6.83076902 -1.71475835  4.12475995]
[ 8.25  0.5   5.25  9.5  18.    5.5   3.75  0.45  4.5   4.5   2.7   0.72
  5.

In [ ]:
accuracy = regressor.score(X_test, y_test)
print(accuracy)

0.8639362504420987


## * I have first uploaded the dataset file on google drive
## https://drive.google.com/file/d/1tzV9vkxEx6e7jytcz3HR7pT482D6BcxA/view?usp=sharing
* Made this dataset file public (anyone to view)
* Fetched this dataset file from google drive to google colab notebook by
** FILE_ID is the part between /d/ and /view of the link of the dataset
** Replacing FILE_ID with the actual ID from our link
** file_id = "File_Id_here"
** file_url = f"https://drive.google.com/uc?id={file_id}"
## dataset = pandas.read	_csv(file_url)